[book]
title = "nix-book"
authors = ["saylesss88"]
language = "en"
src = "src"

[preprocessor.rss-feed]
renderers = ["html"]

[preprocessor.frontmatter-strip]
command = "mdbook-frontmatter-strip"
renderers = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderers = ["html"]

[output.html]
# theme = "navy"
# default-theme = "navy"
site-url = "https://saylesss88.github.io/"
additional-css = ["theme/extra.css", "theme/header-buttons.css"]
additional-js = ["theme/extra.js", "theme/header-buttons.js"]

[output.html.code]
hidelines = {nix = "~"}

[output.html.print]
enable = true
